name: SNIPER813PRO DOMI ENGINE

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5 # Updated to fix Node 20 warning

      - name: Set up Python 3.11
        uses: actions/setup-python@v6 # Updated to fix Node 20 warning
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy google-genai 

      - name: Execute SNIPER813PRO
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KRAKEN_REF_LINK: ${{ secrets.KRAKEN_REF_LINK }}
          # MAP YOUR UNIQUE SECRET NAME HERE
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY693247102287 }} 
        run: python domi_runner.py
